# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kahoot_mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import settings


class MainMenuWidget(QtWidgets.QWidget):
    def __init__(self, *args, **kwargs):
        super(MainMenuWidget, self).__init__(*args, **kwargs)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.battery_frame = QtWidgets.QFrame(self.frame_2)
        self.battery_frame.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.battery_frame.setFont(font)
        self.battery_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.battery_frame.setStyleSheet("QFrame{\n"
"    border-style: solid;\n"
"    border-color: #ffffff;\n"
"    border-width: 10px;\n"
"}\n")
        self.battery_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.battery_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.battery_frame.setObjectName("battery_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.battery_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_32 = QtWidgets.QLabel(self.battery_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(0, 80))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("QLabel{\n"
"    color: #ffffff;\n"
"    background-color: rgba(0,0,0,0);\n"
"    border-style: solid;\n"
"    border-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-bottom-width: 10px;\n"
"}")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_4.addWidget(self.label_32)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.battery_frame)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgba(0,0,0,0)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_label = QtWidgets.QLabel(self.frame_3)
        self.img_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        self.img_label.setFont(font)
        self.img_label.setStyleSheet("background-color: #ffffff;")
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.horizontalLayout_2.addWidget(self.img_label)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_label = QtWidgets.QLabel(self.frame_4)
        self.logo_label.setMaximumSize(QtCore.QSize(160, 160))
        self.logo_label.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 10px;\n"
"    border-color:  #fea125;\n"
"    background-color: #ffffff;\n"
"    border-radius: 79px;\n"
"    color: #000000;\n"
"}")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_3.addWidget(self.logo_label)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet('color: white')
        self.horizontalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.start_bt = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_bt.sizePolicy().hasHeightForWidth())
        self.start_bt.setSizePolicy(sizePolicy)
        self.start_bt.setMinimumSize(QtCore.QSize(0, 160))
        self.start_bt.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.start_bt.setFont(font)
        self.start_bt.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"    border-width: 10px;\n"
"    border-color:  #0000bb;\n"
"    background-color: #fea125;\n"
"    border-radius: 79px;\n"
"    color: #000000;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-color: #0000ff;\n"
"}")
        self.start_bt.setObjectName("start_bt")
        self.horizontalLayout_4.addWidget(self.start_bt)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.frame_2)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.connect_funcions()

    def connect_funcions(self):
        self.start_bt.pressed.connect(self.start_game)

    def start_game(self):
        settings.stage+=1
        settings.changeStageEvent = True

    def add_team(self, team_name, team_color):
        label = QtWidgets.QLabel(self.battery_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
        label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        label.setFont(font)
        label.setMinimumSize(QtCore.QSize(0, 20))
        label.setMaximumSize(QtCore.QSize(16777215, 40))
        label.setAlignment(QtCore.Qt.AlignCenter)
        label.setText(team_name)
        label.setStyleSheet("QLabel{\n"
f"    background-color: {team_color};\n"
"    border-style: solid;\n"
"    border-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-bottom-width: 4px;\n"
"    color: white;\n"
"}")
        self.verticalLayout_4.insertWidget(1, label)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_32.setText(_translate("Form", "Команды участники"))
        self.label_4.setText(_translate("Form", "Сила внутри"))
        self.start_bt.setText(_translate("Form", "Начать игру"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
