# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kahoot_rating.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import settings


class RatingWidget(QtWidgets.QWidget):
    def __init__(self, *args, **kwargs):
        super(RatingWidget, self).__init__(*args, **kwargs)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self)
        self.label.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet("color: #0F1108")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.frame_2.setFont(font)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.bt_back = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_back.sizePolicy().hasHeightForWidth())
        self.bt_back.setSizePolicy(sizePolicy)
        self.bt_back.setMinimumSize(QtCore.QSize(360, 180))
        self.bt_back.setMaximumSize(QtCore.QSize(360, 180))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bt_back.setFont(font)
        self.bt_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_back.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-color:  #0000bb;\n"
"    background-color: #92BCEA;\n"
"    border-radius: 90px;\n"
"    color: #000000;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #C0D5EC;\n"  
"}\n"
"QPushButton:pressed{\n"
"    background-color: #334195;\n"
"}")
        pixmap = QtGui.QPixmap("img/back.png")
        ButtonIcon = QtGui.QIcon(pixmap)
        self.bt_back.setIcon(ButtonIcon)
        self.bt_back.setIconSize(pixmap.rect().size()/4)
        self.bt_back.setObjectName("bt_back")
        self.verticalLayout_3.addWidget(self.bt_back)
        self.horizontalLayout.addWidget(self.frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.battery_frame = QtWidgets.QFrame(self)
        self.battery_frame.setMinimumSize(QtCore.QSize(800, 800))
        self.battery_frame.setMaximumSize(QtCore.QSize(800, 800))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.battery_frame.setFont(font)
        self.battery_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.battery_frame.setStyleSheet("QFrame{\n"
"    border-style: solid;\n"
"    border-color: #0F1108;\n"
"    border-width: 10px;\n"
"}\n"
"QLabel{\n"
"    background-color: red;\n"
"    border-style: solid;\n"
"    border-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-bottom-width: 4px;\n"
"}")
        self.battery_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.battery_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.battery_frame.setObjectName("battery_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.battery_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.battery_frame)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.bt_forward = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_forward.sizePolicy().hasHeightForWidth())
        self.bt_forward.setSizePolicy(sizePolicy)
        self.bt_forward.setMinimumSize(QtCore.QSize(360, 180))
        self.bt_forward.setMaximumSize(QtCore.QSize(360, 180))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bt_forward.setFont(font)
        self.bt_forward.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_forward.setStyleSheet("QPushButton{\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-color:  #0000bb;\n"
"    background-color: #92BCEA;\n"
"    border-radius: 90px;\n"
"    color: #000000;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #C0D5EC;\n"  
"}\n"
"QPushButton:pressed{\n"
"    background-color: #334195;\n"
"}")
        pixmap = QtGui.QPixmap("img/forward.png")
        ButtonIcon = QtGui.QIcon(pixmap)
        self.bt_forward.setIcon(ButtonIcon)
        self.bt_forward.setIconSize(pixmap.rect().size()/4)
        self.bt_forward.setObjectName("bt_forward")
        self.verticalLayout_2.addWidget(self.bt_forward)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.connect_funcions()

    def connect_funcions(self):
        self.bt_back.pressed.connect(self.page_down)
        self.bt_forward.pressed.connect(self.page_up)

    def page_up(self):
        settings.stage+=1
        settings.changeStageEvent = True

    def page_down(self):
        settings.stage-=1
        settings.changeStageEvent = True

    def add_team(self, position, team_name, team_color, team_score):
        label = QtWidgets.QLabel(self.battery_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
        label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        label.setFont(font)
        label.setMinimumSize(QtCore.QSize(0, 20))
        label.setMaximumSize(QtCore.QSize(16777215, 40))
        label.setAlignment(QtCore.Qt.AlignCenter)
        label.setText(f"{position}. {team_name}\t {team_score}")
        label.setStyleSheet("QLabel{\n"
f"    background-color: {team_color};\n"
"    border-style: solid;\n"
"    border-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-bottom-width: 4px;\n"
"    color: white;\n"
"}")
        self.verticalLayout_4.insertWidget(0, label)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Промежуточный рейтинг"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
